name: Test and Deploy preview
on:
  pull_request:
    branches-ignore:
      - main
      - staging
  push:
    branches-ignore:
      - main
      - staging
permissions:
  pull-requests: write
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.extract_branch.outputs.branch }}
    steps:
      - uses: actions/checkout@v3
      - name: Extract Branch Name
        id: extract_branch
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${{ github.head_ref }} | tr '/' '-')"
  deploy-preview:
    runs-on: ubuntu-latest
    needs: setup
    if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize')
    steps:
      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Branch Name is ${{ needs.setup.outputs.branch_name }}.'
            })
