name: Test and Deploy preview
on:
  pull_request:
    branches-ignore:
      - main
  push:
    branches-ignore:
      - main
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.extract_branch.outputs.branch }}
    steps:
      - uses: actions/checkout@v3
      - name: Extract Branch Name
        id: extract_branch
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${{ github.head_ref }} | tr '/' '-')"
  test:
    if: github.event_name != 'pull_request' || github.event.action != 'closed'
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: echo "Test"
      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: 17
          body: |
            Branch name
            ${{ needs.setup.outputs.branch_name }}
            PR
            ${{ github.event.pull_request.number }}
