name: Test and Deploy preview
on:
  pull_request:
    branches-ignore:
      - main
  push:
    branches-ignore:
      - main
jobs:
  test:
    if: github.event_name != 'pull_request' || github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Extract Branch Name
        id: extract_branch
        run: echo "branch=${{ github.head_ref }}" >> $GITHUB_ENV

      - name: Use Branch Name
        run: |
          echo "The br
