name: Test and Deploy preview
on:
  pull_request:
    branches-ignore:
      - main
  push:
    branches-ignore:
      - main
jobs:
  test:
    if: github.event_name != 'pull_request' || github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo PR #${{ github.event.number }} ${GITHUB_REF} ${GITHUB_SHA}
