name: Test and Deploy preview
on:
  pull_request:
    branches-ignore:
      - main
  push:
    branches-ignore:
      - main
permissions:
  pull-requests: write
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.extract_branch.outputs.branch }}
    steps:
      - uses: actions/checkout@v3
      - name: Extract Branch Name
        id: extract_branch
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${{ github.head_ref }} | tr '/' '-')"
  test:
    if: github.event_name != 'pull_request' || github.event.action != 'closed'
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Comment on PR
        uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const prNumber = context.payload.pull_request.number;
            github.issues.createComment({
              issue_number: prNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Branch name is ${{needs.setup.outputs.branch_name}}.`
            });
